= Docker demo
:author: Lorenzo Luconi Trombacchi, Cristian Lucchesi
Linux Day Pisa - 22 ottobre 2016

== Installazione Docker Engine

Docker Engine is supported on Linux, Cloud, Windows, and macOS.

Istruzioni di installazione:

 * https://docs.docker.com/engine/installation/
 

== Docker demo

[source,bash]
----
$ docker version
----

----
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
----


== Hello World

[source,bash]
----
$ docker run busybox echo hello world
----

----
hello world
----

== Un container un più "grande"

[source,bash]
----
$ docker run -it ubuntu bash
----

----
root@65aa81c2de9b:/# 
----

This is a brand new container.

 * It runs a bare-bones, no-frills ubuntu system.
 * -it is shorthand for -i -t.
 * -i tells Docker to connect us to the container's stdin.
 * -t tells Docker that we want a pseudo-terminal.

== Eseguire qualcosa nel container

[source,bash]
----
root@65aa81c2de9b:/# figlet hello
----

----
bash: figlet: command not found
----

Giusto! dobbiamo prima installare figlet

== Installare un pacchetto

[source,bash]
----
root@65aa81c2de9b:/# apt-get update
----

----
...
Fetched 24.4 MB in 1s (13.1 MB/s)                          
Reading package lists... Done
----

[source,bash]
----
root@65aa81c2de9b:/# apt-get install figlet
----

----
Reading package lists... Done
....
----

figlet è installato!

[source,bash]
----
root@65aa81c2de9b:/# figlet hello world
----

----
| |__   ___| | | ___   __      _____  _ __| | __| |
| '_ \ / _ \ | |/ _ \  \ \ /\ / / _ \| '__| |/ _` |
| | | |  __/ | | (_) |  \ V  V / (_) | |  | | (_| |
|_| |_|\___|_|_|\___/    \_/\_/ \___/|_|  |_|\__,_|
----

== Exiting our container

Just exit the shell, like you would usually do.

(E.g. with ^D or exit)

[source,bash]
----
root@04c0bb0a6c07:/# exit
----

 * Our container is now in a stopped state.
 * It still exists on disk, but all compute resources have been freed up.

== Starting another container

Se avviamo un nuovo container e proviamo ad eseguire ancora figlet?

[source,bash]
----
$ docker run -it ubuntu bash
----
----
root@b13c164401fb:/# figlet
bash: figlet: command not found
----

 * Abbiamo avviato un container completamente nuovo
 * E' stata utilizzata l'immagine base di Ubuntu e figlet non è compreso
 * vedremo successivamente come preparere una propria immagine contenente figlet

[source,bash]
----
root@b13c164401fb:/# exit
----

== Docker ps/start/attach/--name/rm

[source,bash]
----
$ docker ps
$ docker ps -a
$ docker start  ecfa855752d5 #niente terminale!
$ docker ps
$ docker attach ecfa855752d5
$ docker run -it --name ubuntu ubuntu bash #poi exit
$ docker rm -f bash
----

== Non-interactive container

[source,bash]
----
$ docker run --rm --name clock jpetazzo/clock #stopped all'uscita
$ docker run --name clock -d jpetazzo/clock
$ docker ps
$ docker logs clock
$ docker logs -f clock
$ docker kill clock
----

== Immagini docker e registri

[source,bash]
----
$ docker images
$ docker search postgres
$ docker search criluc
$ docker pull debian:jessie #:latest default tag se non specificato
----

== DockerFile

 * il Dockerfile è una ricetta per costruire un'immagine
 * contiene una serie di istruzioni con le quali costruire l'immagine
 * il comando *docker build* costruisce l'immagine a partire dal Dockerfile.

[source,bash]
----
$ mkdir /var/tmp/myimage && cd /var/tmp/myimage
$ vi Dockerfile
----

----
FROM ubuntu
RUN apt-get update
RUN apt-get install figlet
----

[source,bash]
----
$ docker build -t figlet .
----

== Dockerfile ^cont^

[source,bash]
----
$ docker history figlet
----

[source,bash]
----
$ docker run -rm figlet figlet Linux Day
----

Aggiungendo un ENTRYPOINT al Dockerfile...
----
ENTRYPOINT["figlet"]
----

----
$ docker build -t figlet .
----

----
$ docker run -rm figlet Linux Day
----

== Docker port

[source,bash]
----
$ docker run --name nginx -d -p 81:80 -p 443:443 nginx
----

----
$ docker ps
----

----
$ curl localhost:81
----

 * -p 80:81 informa di fare mappare la porta 80 del container docker sulla porta 80 dell'host ospitante
  ** i Containers non hanno indirizzi IP pubblici ma solo privati
  ** i servizi devono essere esposti porta per porta
  ** le porte deveono essere mappate per evitare conflitti
 
== Docker volume

----
$ docker run -p 81:80 \
  -v ${PWD}/src/examples/:/usr/share/nginx/html nginx
----


== Slide

Queste slide sono disponibili su https://criluc.github.io/docker-ld2016/

Lorenzo Luconi Trombacchi <lorenzo.luconi@iit.cnr.it>
Cristian Lucchesi <cristian.lucchesi@iit.cnr.it>



